# Sidebar navigation

- label: 'Getting Started'
  link: '/'
- label: 'Concepts'
  link: '/concepts'
- label: 'Theming'
  link: '/theming'
- label: 'Utilities'
  link: '/utilities'
- label: 'Theme Builder ⚠️'
  link: '/theme-builder'
  external: true
# - label: Elements
#   items:
#     - label: 'Button'
#       link: '/elements/Button'
#     - label: 'Checkbox'
#       link: '/elements/Checkbox'
#     - label: 'Heading'
#       link: '/elements/Heading'
# - label: Examples
#   items:
#     - label: 'Buttons'
#       link: '/examples/Buttons'
#     - label: 'Cards'
#       link: '/examples/Cards'
#     - label: 'Forms'
#       link: '/examples/Forms'
#     - label: 'Modals'
#       link: '/examples/Modals'
#     - label: 'Navigation'
#       link: '/examples/Navigation'
