# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: 'Theming'
  link: '/theming'
- label: 'Utilities'
  link: '/utilities'
- label: 'Theme Builder ⚠️'
  link: '/theme-editor'
- label: Elements
  items:
    - label: 'Button'
      link: '/elements/Button'
    - label: 'Checkbox'
      link: '/elements/Checkbox'
- label: Examples
  items:
    - label: 'Buttons'
      link: '/examples/Buttons'
    - label: 'Cards'
      link: '/examples/Cards'
    - label: 'Forms'
      link: '/examples/Forms'
    - label: 'Modals'
      link: '/examples/Modals'
    - label: 'Navigation'
      link: '/examples/Navigation'
