name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish NPM Package
      run: |
        yarn install
        yarn test
        yarn semantic-release
